"""second migration

Revision ID: 26f66861afba
Revises: 
Create Date: 2017-09-07 06:55:28.901335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26f66861afba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_teacher', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_users_is_teacher'), 'users', ['is_teacher'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_is_teacher'), table_name='users')
    op.drop_column('users', 'is_teacher')
    # ### end Alembic commands ###
